TRAIN_DATA = [
    ("The technology sector is growing rapidly.", {"entities": [(4, 15, "SECTOR")]}),
    ("Investing in finance can be very lucrative.", {"entities": [(10, 17, "SECTOR")]}),
    ("Healthcare has seen tremendous advances.", {"entities": [(0, 10, "SECTOR")]}),
    ("The energy sector is crucial for sustainability.", {"entities": [(4, 10, "SECTOR")]}),
    ("The automotive industry is evolving with electric cars.", {"entities": [(4, 13, "SECTOR")]}),
    ("Agriculture plays a vital role in the economy.", {"entities": [(0, 11, "SECTOR")]}),
    ("The retail sector is adapting to online shopping trends.", {"entities": [(4, 10, "SECTOR")]}),
    ("Education is crucial for personal development.", {"entities": [(0, 9, "SECTOR")]}),
    ("The entertainment industry is booming with new media.", {"entities": [(4, 14, "SECTOR")]}),
    ("Pharmaceutical companies are advancing drug development.", {"entities": [(0, 14, "SECTOR")]}),
    ("Real estate investments are increasing in urban areas.", {"entities": [(0, 11, "SECTOR")]}),
    ("Tourism contributes significantly to the local economy.", {"entities": [(0, 7, "SECTOR")]}),
    ("The construction industry is seeing a rise in demand.", {"entities": [(4, 13, "SECTOR")]}),
    ("Telecommunications is essential for modern connectivity.", {"entities": [(0, 15, "SECTOR")]}),
    ("The aerospace sector involves complex technologies.", {"entities": [(4, 12, "SECTOR")]}),
    ("Biotechnology has made significant breakthroughs recently.", {"entities": [(0, 13, "SECTOR")]}),
    ("Insurance provides financial security for individuals.", {"entities": [(0, 8, "SECTOR")]}),
    ("The mining industry is vital for resource extraction.", {"entities": [(4, 9, "SECTOR")]}),
    ("Fashion trends change rapidly with consumer preferences.", {"entities": [(0, 7, "SECTOR")]}),
    ("The automotive sector is focusing on sustainability.", {"entities": [(4, 13, "SECTOR")]}),
    ("Healthcare services are improving with technology.", {"entities": [(0, 10, "SECTOR")]}),
    ("The chemical industry produces essential materials.", {"entities": [(4, 9, "SECTOR")]}),
    ("The logistics sector is crucial for supply chain management.", {"entities": [(4, 12, "SECTOR")]}),
    ("Financial services are evolving with digital transformation.", {"entities": [(0, 17, "SECTOR")]}),
    ("The defense sector ensures national security.", {"entities": [(4, 11, "SECTOR")]}),
    ("E-commerce is revolutionizing the retail industry.", {"entities": [(0, 9, "SECTOR")]}),
    ("Agricultural technology is advancing food production.", {"entities": [(0, 21, "SECTOR")]}),
    ("The publishing industry is adapting to digital formats.", {"entities": [(4, 12, "SECTOR")]}),
    ("Cybersecurity is becoming increasingly important.", {"entities": [(0, 11, "SECTOR")]}),
    ("The automotive market is expanding globally.", {"entities": [(4, 12, "SECTOR")]}),
    ("Renewable energy is gaining traction worldwide.", {"entities": [(0, 16, "SECTOR")]}),
    ("The healthcare sector is growing with new innovations.", {"entities": [(4, 12, "SECTOR")]}),
    ("Transportation infrastructure needs ongoing investment.", {"entities": [(0, 13, "SECTOR")]}),
    ("The financial sector is recovering from recent challenges.", {"entities": [(4, 12, "SECTOR")]}),
    ("Artificial intelligence is transforming various industries.", {"entities": [(0, 19, "SECTOR")]}),
    ("The agriculture sector benefits from advanced technology.", {"entities": [(4, 14, "SECTOR")]}),
    ("Retail companies are leveraging big data for customer insights.", {"entities": [(0, 6, "SECTOR")]}),
    ("The entertainment industry is exploring virtual reality.", {"entities": [(4, 14, "SECTOR")]}),
    ("Medical research is crucial for disease prevention.", {"entities": [(0, 7, "SECTOR")]}),
    ("The energy market is shifting towards greener alternatives.", {"entities": [(4, 10, "SECTOR")]}),
    ("Construction companies are investing in smart buildings.", {"entities": [(0, 11, "SECTOR")]}),
    ("Financial technology is evolving rapidly.", {"entities": [(0, 15, "SECTOR")]}),
    ("The textile industry is exploring sustainable practices.", {"entities": [(4, 11, "SECTOR")]}),
    ("Transportation services are enhancing user experience.", {"entities": [(0, 13, "SECTOR")]}),
    ("The pharmaceutical sector is researching new treatments.", {"entities": [(4, 14, "SECTOR")]}),
    ("Media and communications are shaping public opinion.", {"entities": [(0, 5, "SECTOR")]}),
    ("The hospitality industry is focusing on personalized experiences.", {"entities": [(4, 12, "SECTOR")]}),
    ("Smart home technology is revolutionizing daily living.", {"entities": [(0, 13, "SECTOR")]}),
    ("Fintech is changing the way people manage their money.", {"entities": [(0, 6, "SECTOR")]}),
    ("The robotics sector is advancing automation in manufacturing.", {"entities": [(4, 11, "SECTOR")]}),
    ("Healthcare providers are adopting telemedicine.", {"entities": [(0, 10, "SECTOR")]}),
    ("The real estate market is experiencing fluctuations.", {"entities": [(4, 11, "SECTOR")]}),
    ("The gaming industry is expanding with virtual reality.", {"entities": [(4, 10, "SECTOR")]}),
    ("The renewable energy sector is crucial for sustainability.", {"entities": [(4, 17, "SECTOR")]}),
    ("The agricultural sector is vital for food security.", {"entities": [(4, 14, "SECTOR")]}),
    ("Retailers are embracing omnichannel strategies.", {"entities": [(0, 6, "SECTOR")]}),
    ("Education technology is enhancing learning experiences.", {"entities": [(0, 15, "SECTOR")]}),
    ("The biotechnology industry is focused on innovation.", {"entities": [(4, 13, "SECTOR")]}),
    ("The insurance sector is adapting to changing risks.", {"entities": [(4, 11, "SECTOR")]}),
    ("Telecom services are evolving with 5G technology.", {"entities": [(0, 6, "SECTOR")]}),
    ("The automotive industry is embracing electric vehicles.", {"entities": [(4, 13, "SECTOR")]}),
    ("Healthcare technology is improving patient outcomes.", {"entities": [(0, 10, "SECTOR")]}),
    ("The construction sector is investing in green building practices.", {"entities": [(4, 13, "SECTOR")]}),
    ("The aerospace industry is advancing with new technologies.", {"entities": [(4, 12, "SECTOR")]}),
    ("The financial sector is focusing on regulatory compliance.", {"entities": [(4, 12, "SECTOR")]}),
    ("Agricultural technology is improving crop yields.", {"entities": [(0, 21, "SECTOR")]}),
    ("The entertainment sector is integrating augmented reality.", {"entities": [(4, 12, "SECTOR")]}),
    ("The logistics industry is optimizing supply chain processes.", {"entities": [(4, 12, "SECTOR")]}),
    ("Smart technology is enhancing urban living.", {"entities": [(0, 5, "SECTOR")]}),
    ("The education sector is incorporating digital tools.", {"entities": [(4, 12, "SECTOR")]}),
    ("Biotechnology advancements are transforming medicine.", {"entities": [(0, 13, "SECTOR")]}),
    ("The chemical sector is involved in producing essential products.", {"entities": [(4, 9, "SECTOR")]}),
    ("The media sector is growing with online platforms.", {"entities": [(4, 9, "SECTOR")]}),
    ("Retail technology is advancing with AI-driven analytics.", {"entities": [(0, 6, "SECTOR")]}),
    ("The fintech sector is reshaping financial services.", {"entities": [(4, 10, "SECTOR")]}),
    ("Telecommunications are crucial for global connectivity.", {"entities": [(0, 15, "SECTOR")]}),
    ("The robotics industry is innovating automation processes.", {"entities": [(4, 11, "SECTOR")]}),
    ("Healthcare services are expanding with telehealth options.", {"entities": [(0, 10, "SECTOR")]}),
    ("The insurance industry is leveraging data analytics.", {"entities": [(4, 11, "SECTOR")]}),
    ("The defense industry focuses on national security.", {"entities": [(4, 11, "SECTOR")]}),
    ("Retail sales are increasing with seasonal promotions.", {"entities": [(0, 6, "SECTOR")]}),
    ("The cybersecurity sector is expanding due to rising threats.", {"entities": [(4, 13, "SECTOR")]}),
    ("The aerospace sector is growing with new innovations.", {"entities": [(4, 12, "SECTOR")]}),
    ("The financial services industry is adapting to new regulations.", {"entities": [(4, 17, "SECTOR")]}),
    ("Telecom companies are investing in advanced infrastructure.", {"entities": [(0, 6, "SECTOR")]}),
    ("The renewable energy market is experiencing rapid growth.", {"entities": [(4, 16, "SECTOR")]}),
    ("The agriculture industry is adopting precision farming techniques.", {"entities": [(4, 11, "SECTOR")]}),
    ("Media companies are transitioning to digital formats.", {"entities": [(0, 5, "SECTOR")]}),
    ("The robotics sector is making strides in AI integration.", {"entities": [(4, 11, "SECTOR")]}),
    ("The health tech sector is seeing significant investment.", {"entities": [(4, 8, "SECTOR")]}),
    ("The manufacturing sector is adopting automation.", {"entities": [(4, 11, "SECTOR")]}),
    ("The automotive sector is focusing on autonomous vehicles.", {"entities": [(4, 13, "SECTOR")]}),
    ("Financial technology innovations are disrupting traditional banking.", {"entities": [(0, 15, "SECTOR")]}),
    ("The agricultural sector benefits from biotech advances.", {"entities": [(4, 14, "SECTOR")]}),
    ("Education is evolving with online learning platforms.", {"entities": [(0, 9, "SECTOR")]}),
    ("The retail sector is adjusting to changing consumer behaviors.", {"entities": [(4, 10, "SECTOR")]}),
    ("The defense sector is integrating new technologies.", {"entities": [(4, 11, "SECTOR")]}),
    ("Media companies are exploring new revenue models.", {"entities": [(0, 5, "SECTOR")]}),
    ("The healthcare sector is advancing with wearable technology.", {"entities": [(4, 12, "SECTOR")]}),
    ("The finance industry is adapting to blockchain technology.", {"entities": [(4, 11, "SECTOR")]}),
    ("The construction industry is adopting smart building technologies.", {"entities": [(4, 13, "SECTOR")]}),
    ("The biotech sector is focused on innovative drug development.", {"entities": [(4, 13, "SECTOR")]}),
    ("The education sector is integrating virtual classrooms.", {"entities": [(4, 12, "SECTOR")]}),
    ("Telecom infrastructure is crucial for high-speed internet.", {"entities": [(0, 6, "SECTOR")]}),
    ("The automotive market is exploring hydrogen fuel technology.", {"entities": [(4, 12, "SECTOR")]}),
    ("Retail technology is enhancing customer engagement.", {"entities": [(0, 6, "SECTOR")]}),
    ("The entertainment industry is investing in content creation.", {"entities": [(4, 14, "SECTOR")]}),
    ("Healthcare IT is advancing with electronic health records.", {"entities": [(0, 10, "SECTOR")]}),
    ("The insurance market is innovating with digital platforms.", {"entities": [(4, 11, "SECTOR")]}),
    ("The media industry is embracing new digital formats.", {"entities": [(4, 9, "SECTOR")]}),
    ("The logistics sector is leveraging AI for route optimization.", {"entities": [(4, 12, "SECTOR")]}),
    ("The defense industry is focusing on advanced weaponry.", {"entities": [(4, 11, "SECTOR")]}),
    ("Financial services are integrating AI for fraud detection.", {"entities": [(0, 17, "SECTOR")]}),
    ("The robotics field is making advances in manufacturing automation.", {"entities": [(4, 11, "SECTOR")]}),
    ("The telecommunications sector is evolving with new technologies.", {"entities": [(4, 15, "SECTOR")]}),
    ("The construction market is focusing on sustainable materials.", {"entities": [(4, 13, "SECTOR")]}),
    ("The healthcare industry is investing in personalized medicine.", {"entities": [(4, 12, "SECTOR")]}),
    ("The financial industry is adopting new investment strategies.", {"entities": [(4, 11, "SECTOR")]}),
    ("Retail businesses are using AI for inventory management.", {"entities": [(0, 6, "SECTOR")]}),
    ("The aerospace sector is working on reusable spacecraft.", {"entities": [(4, 12, "SECTOR")]}),
    ("The energy sector is developing new renewable technologies.", {"entities": [(4, 10, "SECTOR")]}),
    ("The biotech industry is exploring gene editing technologies.", {"entities": [(4, 13, "SECTOR")]}),
    ("The education industry is integrating gamification in learning.", {"entities": [(4, 12, "SECTOR")]}),
    ("Telecommunications are essential for remote work solutions.", {"entities": [(0, 15, "SECTOR")]}),
    ("The automotive industry is focusing on electric vehicle infrastructure.", {"entities": [(4, 13, "SECTOR")]}),
    ("Retailers are exploring new e-commerce strategies.", {"entities": [(0, 6, "SECTOR")]}),
    ("The finance sector is improving with automated trading systems.", {"entities": [(4, 12, "SECTOR")]}),
    ("Healthcare research is focusing on precision medicine.", {"entities": [(0, 10, "SECTOR")]}),
    ("The logistics industry is investing in autonomous delivery systems.", {"entities": [(4, 12, "SECTOR")]}),
    ("The media sector is expanding with digital streaming services.", {"entities": [(4, 9, "SECTOR")]}),
    ("The defense sector is integrating advanced surveillance systems.", {"entities": [(4, 11, "SECTOR")]}),
    ("Financial technology is enhancing customer experiences.", {"entities": [(0, 15, "SECTOR")]}),
    ("The energy industry is focusing on smart grid technology.", {"entities": [(4, 5, "SECTOR")]}),
    ("Retail technology is improving with augmented reality tools.", {"entities": [(0, 6, "SECTOR")]}),
    ("The healthcare field is evolving with digital health tools.", {"entities": [(0, 10, "SECTOR")]}),
    ("The aerospace industry is investing in space exploration.", {"entities": [(4, 12, "SECTOR")]}),
    ("Telecommunications are advancing with fiber-optic technology.", {"entities": [(0, 15, "SECTOR")]}),
    ("The insurance sector is utilizing predictive analytics.", {"entities": [(4, 11, "SECTOR")]}),
    ("The biotech sector is researching new vaccine technologies.", {"entities": [(4, 13, "SECTOR")]}),
    ("Retail companies are adopting AI for personalized marketing.", {"entities": [(0, 6, "SECTOR")]}),
    ("The construction industry is focusing on green building standards.", {"entities": [(4, 13, "SECTOR")]}),
    ("Financial services are enhancing with blockchain solutions.", {"entities": [(0, 17, "SECTOR")]}),
    ("The media industry is innovating with interactive content.", {"entities": [(4, 9, "SECTOR")]}),
    ("Healthcare providers are adopting new AI diagnostics.", {"entities": [(0, 10, "SECTOR")]}),
    ("The logistics sector is utilizing drones for deliveries.", {"entities": [(4, 12, "SECTOR")]}),
    ("The automotive market is integrating advanced driver assistance systems.", {"entities": [(4, 12, "SECTOR")]}),
    ("Retailers are exploring virtual reality shopping experiences.", {"entities": [(0, 6, "SECTOR")]}),
    ("The aerospace sector is developing next-generation aircraft.", {"entities": [(4, 12, "SECTOR")]}),
    ("Telecommunications are crucial for 5G network deployment.", {"entities": [(0, 15, "SECTOR")]}),
    ("The defense industry is enhancing cybersecurity measures.", {"entities": [(4, 11, "SECTOR")]}),
    ("The energy sector is investing in hydrogen fuel cells.", {"entities": [(4, 10, "SECTOR")]}),
    ("Retail technology is improving supply chain management.", {"entities": [(0, 6, "SECTOR")]}),
    ("The financial sector is adapting to new digital payment solutions.", {"entities": [(4, 12, "SECTOR")]}),
    ("The healthcare field is focusing on telehealth services.", {"entities": [(0, 10, "SECTOR")]}),
    ("The media industry is expanding with social media platforms.", {"entities": [(4, 9, "SECTOR")]}),
    ("The logistics sector is implementing smart warehousing solutions.", {"entities": [(4, 12, "SECTOR")]}),
    ("The defense sector is innovating with autonomous systems.", {"entities": [(4, 11, "SECTOR")]}),
    ("Retail businesses are enhancing customer experience with AI.", {"entities": [(0, 6, "SECTOR")]}),
    ("The biotech industry is advancing with new gene therapies.", {"entities": [(4, 13, "SECTOR")]}),
    ("The energy industry is focusing on geothermal power.", {"entities": [(4, 5, "SECTOR")]}),
    ("The telecommunications sector is evolving with satellite technology.", {"entities": [(4, 15, "SECTOR")]}),
    ("Healthcare technology is making strides in wearable devices.", {"entities": [(0, 10, "SECTOR")]}),
    ("The financial industry is integrating AI for investment strategies.", {"entities": [(4, 11, "SECTOR")]}),
    ("Retailers are adopting advanced analytics for demand forecasting.", {"entities": [(0, 6, "SECTOR")]}),
    ("The aerospace field is focusing on sustainable aviation.", {"entities": [(4, 12, "SECTOR")]}),
    ("The construction sector is incorporating green building materials.", {"entities": [(4, 13, "SECTOR")]}),
    ("The media industry is leveraging big data for audience insights.", {"entities": [(4, 9, "SECTOR")]}),
    ("Healthcare services are integrating AI-driven health assessments.", {"entities": [(0, 10, "SECTOR")]}),
    ("The insurance market is adopting digital claims processing.", {"entities": [(4, 11, "SECTOR")]}),
    ("The defense industry is developing next-gen surveillance technology.", {"entities": [(4, 11, "SECTOR")]}),
    ("Retail technology is advancing with smart checkout systems.", {"entities": [(0, 6, "SECTOR")]}),
    ("The biotech sector is researching regenerative medicine.", {"entities": [(4, 13, "SECTOR")]}),
    ("The energy sector is expanding with wind power initiatives.", {"entities": [(4, 10, "SECTOR")]}),
    ("Telecom companies are enhancing network coverage.", {"entities": [(0, 6, "SECTOR")]}),
    ("The healthcare field is evolving with digital health records.", {"entities": [(0, 10, "SECTOR")]}),
    ("The financial services sector is embracing new technologies.", {"entities": [(4, 17, "SECTOR")]}),
    ("The aerospace industry is investing in space tourism.", {"entities": [(4, 12, "SECTOR")]}),
    ("Retailers are using AI to personalize shopping experiences.", {"entities": [(0, 6, "SECTOR")]}),
    ("The biotech industry is advancing with CRISPR technology.", {"entities": [(4, 13, "SECTOR")]}),
    ("The construction industry is investing in smart infrastructure.", {"entities": [(4, 13, "SECTOR")]}),
    ("Telecommunications are essential for global communication.", {"entities": [(0, 15, "SECTOR")]}),
    ("The energy sector is developing advanced battery storage.", {"entities": [(4, 10, "SECTOR")]}),
    ("The media industry is focusing on interactive storytelling.", {"entities": [(4, 9, "SECTOR")]}),
    ("Healthcare technology is improving with AI diagnostics.", {"entities": [(0, 10, "SECTOR")]}),
    ("The financial sector is exploring new trading algorithms.", {"entities": [(4, 12, "SECTOR")]}),
    ("Retail technology is enhancing inventory management.", {"entities": [(0, 6, "SECTOR")]}),
    ("The aerospace field is advancing with satellite technologies.", {"entities": [(4, 12, "SECTOR")]}),
    ("The defense industry is investing in autonomous vehicles.", {"entities": [(4, 11, "SECTOR")]}),
    ("Telecommunications are evolving with 5G technology.", {"entities": [(0, 15, "SECTOR")]}),
    ("The healthcare industry is expanding with home health monitoring.", {"entities": [(4, 12, "SECTOR")]}),
    ("Retailers are leveraging big data for customer analytics.", {"entities": [(0, 6, "SECTOR")]}),
    ("The energy sector is focusing on solar power advancements.", {"entities": [(4, 10, "SECTOR")]}),
    ("The media sector is innovating with augmented reality content.", {"entities": [(4, 9, "SECTOR")]}),
    ("The construction industry is adopting modular building techniques.", {"entities": [(4, 13, "SECTOR")]}),
    ("The biotech industry is researching new cancer treatments.", {"entities": [(4, 13, "SECTOR")]}),
    ("The financial services sector is integrating new payment methods.", {"entities": [(4, 17, "SECTOR")]}),
    ("Retail technology is improving with contactless payment systems.", {"entities": [(0, 6, "SECTOR")]}),
    ("The aerospace sector is focusing on next-generation spacecraft.", {"entities": [(4, 12, "SECTOR")]}),
    ("Telecommunications are expanding with fiber-optic networks.", {"entities": [(0, 15, "SECTOR")]}),
    ("The defense sector is integrating advanced radar systems.", {"entities": [(4, 11, "SECTOR")]}),
    ("The healthcare industry is evolving with precision medicine.", {"entities": [(4, 12, "SECTOR")]}),
    ("Retailers are adopting AI for supply chain optimization.", {"entities": [(0, 6, "SECTOR")]}),
    ("The biotech sector is innovating with stem cell research.", {"entities": [(4, 13, "SECTOR")]}),
    ("The energy sector is developing energy-efficient technologies.", {"entities": [(4, 10, "SECTOR")]}),
    ("The media industry is growing with new content platforms.", {"entities": [(4, 9, "SECTOR")]}),
    ("The construction field is focusing on smart city developments.", {"entities": [(4, 11, "SECTOR")]}),
    ("The financial services sector is evolving with robo-advisors.", {"entities": [(4, 17, "SECTOR")]}),
    ("Retail technology is advancing with machine learning algorithms.", {"entities": [(0, 6, "SECTOR")]}),
    ("The aerospace industry is working on reusable rockets.", {"entities": [(4, 12, "SECTOR")]}),
    ("The telecommunications sector is enhancing satellite communications.", {"entities": [(4, 15, "SECTOR")]}),
    ("The defense industry is focusing on next-gen technology solutions.", {"entities": [(4, 11, "SECTOR")]}),
    ("The healthcare sector is investing in AI-powered health tools.", {"entities": [(4, 12, "SECTOR")]}),
    ("The energy industry is adopting advanced solar technologies.", {"entities": [(4, 5, "SECTOR")]}),
    ("Retailers are exploring new virtual shopping experiences.", {"entities": [(0, 6, "SECTOR")]}),
    ("The financial industry is integrating AI for customer service.", {"entities": [(4, 11, "SECTOR")]}),
    ("The biotech sector is advancing with nanotechnology.", {"entities": [(4, 13, "SECTOR")]}),
    ("The media industry is innovating with interactive media.", {"entities": [(4, 9, "SECTOR")]}),
    ("The construction sector is incorporating sustainable practices.", {"entities": [(4, 13, "SECTOR")]}),
    ("The aerospace sector is focused on high-speed transportation.", {"entities": [(4, 12, "SECTOR")]}),
    ("The energy sector is expanding with wind energy projects.", {"entities": [(4, 10, "SECTOR")]}),
    ("Retail technology is enhancing user experience with AI.", {"entities": [(0, 6, "SECTOR")]}),
    ("The financial sector is exploring blockchain for secure transactions.", {"entities": [(4, 12, "SECTOR")]}),
    ("The healthcare field is evolving with AI-driven health solutions.", {"entities": [(0, 10, "SECTOR")]}),
    ("The media industry is adopting new content distribution methods.", {"entities": [(4, 9, "SECTOR")]}),
    ("The logistics sector is leveraging technology for route optimization.", {"entities": [(4, 12, "SECTOR")]}),
    ("The aerospace industry is advancing with space exploration missions.", {"entities": [(4, 12, "SECTOR")]}),
    ("Retail technology is integrating with augmented reality.", {"entities": [(0, 6, "SECTOR")]}),
    ("The defense sector is enhancing capabilities with new tech.", {"entities": [(4, 11, "SECTOR")]}),
    ("The energy industry is investing in renewable energy sources.", {"entities": [(4, 5, "SECTOR")]}),
    ("Healthcare technology is advancing with digital health records.", {"entities": [(0, 10, "SECTOR")]}),
    ("The financial services sector is focusing on fintech solutions.", {"entities": [(4, 17, "SECTOR")]}),
    ("The media industry is exploring new forms of digital engagement.", {"entities": [(4, 9, "SECTOR")]}),
    ("The construction field is innovating with smart infrastructure.", {"entities": [(4, 11, "SECTOR")]}),
    ("The aerospace sector is investing in satellite technologies.", {"entities": [(4, 12, "SECTOR")]}),
    ("Retailers are adopting machine learning for inventory management.", {"entities": [(0, 6, "SECTOR")]}),
    ("The energy sector is focusing on carbon capture technologies.", {"entities": [(4, 10, "SECTOR")]}),
    ("The healthcare industry is investing in AI-driven diagnostics.", {"entities": [(4, 12, "SECTOR")]}),
    ("Telecommunications are expanding with new network technologies.", {"entities": [(0, 15, "SECTOR")]}),
    ("The financial industry is exploring new payment systems.", {"entities": [(4, 11, "SECTOR")]}),
    ("The biotech sector is innovating with new drug delivery methods.", {"entities": [(4, 13, "SECTOR")]}),
    ("The media industry is focusing on interactive and immersive experiences.", {"entities": [(4, 9, "SECTOR")]}),
    ("Retail technology is evolving with blockchain integration.", {"entities": [(0, 6, "SECTOR")]}),
    ("The aerospace industry is advancing with hypersonic travel.", {"entities": [(4, 12, "SECTOR")]}),
    ("The defense sector is developing new cybersecurity measures.", {"entities": [(4, 11, "SECTOR")]}),
    ("The energy industry is investing in smart grid technology.", {"entities": [(4, 5, "SECTOR")]}),
    ("The healthcare sector is expanding with digital therapeutics.", {"entities": [(4, 12, "SECTOR")]}),
    ("Retailers are leveraging AI for customer personalization.", {"entities": [(0, 6, "SECTOR")]}),
    ("The financial services sector is adopting digital identity verification.", {"entities": [(4, 17, "SECTOR")]}),
    ("The aerospace field is focused on next-gen space missions.", {"entities": [(4, 12, "SECTOR")]}),
    ("The biotech industry is advancing with novel therapeutic approaches.", {"entities": [(4, 13, "SECTOR")]}),
    ("The media industry is investing in immersive technologies.", {"entities": [(4, 9, "SECTOR")]}),
    ("Retail technology is incorporating IoT for smarter operations.", {"entities": [(0, 6, "SECTOR")]}),
    ("The energy sector is exploring new geothermal energy technologies.", {"entities": [(4, 10, "SECTOR")]}),
    ("The healthcare field is advancing with robotic surgery.", {"entities": [(0, 10, "SECTOR")]}),
    ("The defense sector is focusing on AI-driven defense systems.", {"entities": [(4, 11, "SECTOR")]}),
    ("Retailers are integrating AI for dynamic pricing strategies.", {"entities": [(0, 6, "SECTOR")]}),
    ("The aerospace industry is investing in advanced propulsion systems.", {"entities": [(4, 12, "SECTOR")]}),
    ("The media sector is enhancing content with virtual reality.", {"entities": [(4, 9, "SECTOR")]}),
    ("The energy industry is focusing on sustainable energy solutions.", {"entities": [(4, 5, "SECTOR")]}),
    ("The financial sector is investing in AI for risk management.", {"entities": [(4, 12, "SECTOR")]}),
    ("Retail technology is evolving with predictive analytics.", {"entities": [(0, 6, "SECTOR")]}),
    ("The aerospace sector is advancing with space habitat research.", {"entities": [(4, 12, "SECTOR")]}),
    ("Telecommunications are advancing with edge computing.", {"entities": [(0, 15, "SECTOR")]}),
    ("The healthcare industry is integrating new wearable devices.", {"entities": [(4, 12, "SECTOR")]}),
    ("The defense sector is focusing on emerging tech for defense applications.", {"entities": [(4, 11, "SECTOR")]}),
    ("Retailers are exploring AI for demand forecasting.", {"entities": [(0, 6, "SECTOR")]}),
    ("The media industry is integrating AR for interactive experiences.", {"entities": [(4, 9, "SECTOR")]}),
    ("The energy sector is developing new energy storage solutions.", {"entities": [(4, 10, "SECTOR")]}),
    ("The aerospace industry is working on advanced satellite systems.", {"entities": [(4, 12, "SECTOR")]}),
    ("Telecommunications are evolving with advanced communication protocols.", {"entities": [(0, 15, "SECTOR")]}),
    ("The healthcare field is advancing with AI-driven health insights.", {"entities": [(0, 10, "SECTOR")]}),
    ("The financial services sector is embracing new digital tools.", {"entities": [(4, 17, "SECTOR")]}),
    ("Retailers are utilizing big data for better customer segmentation.", {"entities": [(0, 6, "SECTOR")]}),
    ("The aerospace field is innovating with reusable launch systems.", {"entities": [(4, 12, "SECTOR")]}),
    ("The media industry is focusing on next-gen content delivery.", {"entities": [(4, 9, "SECTOR")]}),
    ("The energy industry is investing in next-generation battery technology.", {"entities": [(4, 5, "SECTOR")]}),
    ("Retail technology is improving with advanced AI algorithms.", {"entities": [(0, 6, "SECTOR")]}),
    ("The biotech sector is developing new treatment methodologies.", {"entities": [(4, 13, "SECTOR")]}),
    ("The construction industry is investing in sustainable building practices.", {"entities": [(4, 13, "SECTOR")]}),
    ("The financial sector is focusing on next-gen investment platforms.", {"entities": [(4, 12, "SECTOR")]}),
    ("Retail technology is advancing with smart supply chain solutions.", {"entities": [(0, 6, "SECTOR")]}),
    ("The aerospace sector is developing cutting-edge propulsion technologies.", {"entities": [(4, 12, "SECTOR")]}),
    ("The media industry is integrating VR for immersive storytelling.", {"entities": [(4, 9, "SECTOR")]}),
    ("The energy sector is working on breakthrough solar technologies.", {"entities": [(4, 10, "SECTOR")]}),
    ("Retailers are enhancing experiences with AI-driven insights.", {"entities": [(0, 6, "SECTOR")]}),
    ("The financial services sector is innovating with digital banking solutions.", {"entities": [(4, 17, "SECTOR")]}),
    ("The aerospace industry is investing in cutting-edge satellite technology.", {"entities": [(4, 12, "SECTOR")]}),
    ("The defense sector is incorporating AI for advanced threat detection.", {"entities": [(4, 11, "SECTOR")]}),
    ("Retail technology is evolving with machine learning for inventory.", {"entities": [(0, 6, "SECTOR")]}),
    ("The energy industry is focusing on smart grid innovations.", {"entities": [(4, 5, "SECTOR")]}),
    ("The healthcare field is integrating advanced AI tools for diagnostics.", {"entities": [(0, 10, "SECTOR")]}),
    ("The media industry is exploring new interactive formats.", {"entities": [(4, 9, "SECTOR")]}),
    ("Retailers are implementing AI for real-time data analysis.", {"entities": [(0, 6, "SECTOR")]}),
    ("The aerospace sector is advancing with new space exploration technologies.", {"entities": [(4, 12, "SECTOR")]}),
    ("Telecommunications are enhancing connectivity with new infrastructure.", {"entities": [(0, 15, "SECTOR")]}),
    ("The defense sector is focusing on emerging tech for defense.", {"entities": [(4, 11, "SECTOR")]}),
    ("The energy industry is developing new energy efficiency technologies.", {"entities": [(4, 5, "SECTOR")]}),
    ("Retail technology is advancing with digital transformation.", {"entities": [(0, 6, "SECTOR")]}),
    ("The financial services sector is leveraging AI for personalized solutions.", {"entities": [(4, 17, "SECTOR")]}),
    ("The aerospace industry is developing advanced satellite communications.", {"entities": [(4, 12, "SECTOR")]}),
    ("The media sector is expanding with new immersive technologies.", {"entities": [(4, 9, "SECTOR")]}),
    ("The construction field is innovating with sustainable urban planning.", {"entities": [(4, 11, "SECTOR")]}),
    ("The financial sector is investing in next-gen investment platforms.", {"entities": [(4, 12, "SECTOR")]}),
    ("Retail technology is evolving with AI-powered tools.", {"entities": [(0, 6, "SECTOR")]}),
    ("The energy industry is focusing on advanced renewable technologies.", {"entities": [(4, 5, "SECTOR")]}),
    ("The aerospace sector is investing in cutting-edge propulsion systems.", {"entities": [(4, 12, "SECTOR")]}),
    ("The defense sector is enhancing capabilities with advanced AI.", {"entities": [(4, 11, "SECTOR")]}),
    ("Retail technology is improving with smart retail solutions.", {"entities": [(0, 6, "SECTOR")]}),
    ("The media industry is innovating with new digital experiences.", {"entities": [(4, 9, "SECTOR")]}),
    ("The biotech sector is focusing on breakthrough medical research.", {"entities": [(4, 13, "SECTOR")]}),
    ("The construction industry is advancing with eco-friendly practices.", {"entities": [(4, 13, "SECTOR")]}),
    ("The financial services sector is evolving with next-gen financial tools.", {"entities": [(4, 17, "SECTOR")]}),
    ("Retail technology is advancing with innovative shopping experiences.", {"entities": [(0, 6, "SECTOR")]}),
    ("The aerospace industry is developing new technologies for space exploration.", {"entities": [(4, 12, "SECTOR")]}),
    ("The energy sector is investing in advanced geothermal technologies.", {"entities": [(4, 10, "SECTOR")]}),
    ("The media industry is expanding with new virtual reality platforms.", {"entities": [(4, 9, "SECTOR")]}),
    ("The defense sector is integrating new technologies for enhanced security.", {"entities": [(4, 11, "SECTOR")]}),
    ("Retail technology is innovating with smart store solutions.", {"entities": [(0, 6, "SECTOR")]}),
    ("The healthcare industry is advancing with AI-driven patient care.", {"entities": [(4, 12, "SECTOR")]}),
    ("The financial sector is exploring new investment opportunities with AI.", {"entities": [(4, 12, "SECTOR")]}),
    ("The aerospace sector is working on next-gen propulsion technologies.", {"entities": [(4, 12, "SECTOR")]}),
    ("The energy industry is developing advanced solar energy solutions.", {"entities": [(4, 5, "SECTOR")]}),
    ("Retail technology is advancing with AI-enhanced customer experiences.", {"entities": [(0, 6, "SECTOR")]}),
    ("The media industry is focusing on new digital engagement strategies.", {"entities": [(4, 9, "SECTOR")]}),
    ("The biotech sector is innovating with new treatment methodologies.", {"entities": [(4, 13, "SECTOR")]}),
    ("The healthcare field is advancing with new medical devices.", {"entities": [(0, 10, "SECTOR")]}),
    ("The financial services sector is integrating AI for fraud detection.", {"entities": [(4, 17, "SECTOR")]}),
    ("Retail technology is evolving with digital transformation.", {"entities": [(0, 6, "SECTOR")]}),
    ("The aerospace industry is advancing with satellite-based systems.", {"entities": [(4, 12, "SECTOR")]}),
    ("The energy industry is investing in advanced storage technologies.", {"entities": [(4, 5, "SECTOR")]}),
    ("The media industry is innovating with new forms of digital media.", {"entities": [(4, 9, "SECTOR")]}),
    ("The financial sector is focusing on blockchain-based solutions.", {"entities": [(4, 12, "SECTOR")]}),
    ("Retailers are advancing with AI for personalized shopping experiences.", {"entities": [(0, 6, "SECTOR")]}),
    ("The aerospace field is investing in advanced space travel technologies.", {"entities": [(4, 12, "SECTOR")]}),
    ("The defense sector is focusing on emerging tech for security applications.", {"entities": [(4, 11, "SECTOR")]}),
    ("The healthcare industry is evolving with telemedicine.", {"entities": [(4, 12, "SECTOR")]}),
    ("The energy sector is expanding with innovative energy solutions.", {"entities": [(4, 10, "SECTOR")]}),
    ("Retail technology is incorporating AI for enhanced customer engagement.", {"entities": [(0, 6, "SECTOR")]}),
    ("The financial services sector is integrating AI for personalized investment strategies.", {"entities": [(4, 17, "SECTOR")]}),
    ("The media industry is focusing on next-gen content creation.", {"entities": [(4, 9, "SECTOR")]}),
    ("The aerospace sector is working on cutting-edge space technology.", {"entities": [(4, 12, "SECTOR")]}),
    ("Retailers are innovating with new AI-driven shopping experiences.", {"entities": [(0, 6, "SECTOR")]}),
    ("The defense sector is enhancing its capabilities with advanced AI technologies.", {"entities": [(4, 11, "SECTOR")]}),
    ("The energy industry is focusing on advanced renewable energy technologies.", {"entities": [(4, 5, "SECTOR")]}),
    ("The healthcare field is advancing with precision medicine.", {"entities": [(0, 10, "SECTOR")]}),
    ("The financial sector is exploring new AI-driven solutions.", {"entities": [(4, 12, "SECTOR")]}),
    ("The media industry is expanding with innovative digital platforms.", {"entities": [(4, 9, "SECTOR")]}),
    ("The aerospace industry is focusing on advanced satellite systems.", {"entities": [(4, 12, "SECTOR")]}),
    ("The defense sector is integrating emerging technologies for defense.", {"entities": [(4, 11, "SECTOR")]}),
    ("Retail technology is evolving with next-gen AI tools.", {"entities": [(0, 6, "SECTOR")]}),
    ("The energy sector is developing innovative renewable energy solutions.", {"entities": [(4, 10, "SECTOR")]}),
    ("The healthcare field is focusing on advanced diagnostic tools.", {"entities": [(0, 10, "SECTOR")]}),
    ("The aerospace sector is investing in new space exploration technologies.", {"entities": [(4, 12, "SECTOR")]}),
    ("Retail technology is innovating with smart analytics.", {"entities": [(0, 6, "SECTOR")]}),
    ("The media industry is advancing with virtual reality experiences.", {"entities": [(4, 9, "SECTOR")]}),
    ("The defense industry is enhancing its capabilities with AI-driven solutions.", {"entities": [(4, 11, "SECTOR")]}),
    ("The energy sector is exploring advanced storage technologies.", {"entities": [(4, 10, "SECTOR")]}),
    ("Retail technology is advancing with smart store innovations.", {"entities": [(0, 6, "SECTOR")]}),
    ("The aerospace industry is focusing on next-gen space missions.", {"entities": [(4, 12, "SECTOR")]}),
    ("The media industry is expanding with immersive digital content.", {"entities": [(4, 9, "SECTOR")]}),
    ("The defense sector is integrating AI for advanced security measures.", {"entities": [(4, 11, "SECTOR")]}),
    ("Retailers are leveraging AI for dynamic pricing and inventory management.", {"entities": [(0, 6, "SECTOR")]}),
    ("The healthcare sector is investing in cutting-edge medical technologies.", {"entities": [(4, 12, "SECTOR")]}),
    ("The aerospace industry is advancing with reusable spacecraft.", {"entities": [(4, 12, "SECTOR")]}),
    ("The financial services sector is integrating AI for improved customer service.", {"entities": [(4, 17, "SECTOR")]}),
    ("The energy sector is working on new geothermal energy projects.", {"entities": [(4, 10, "SECTOR")]}),
    ("Retail technology is evolving with machine learning for sales optimization.", {"entities": [(0, 6, "SECTOR")]}),
    ("The media industry is focusing on next-gen immersive experiences.", {"entities": [(4, 9, "SECTOR")]}),
    ("The defense industry is advancing with new cybersecurity technologies.", {"entities": [(4, 11, "SECTOR")]}),
    ("The healthcare field is evolving with AI-powered health solutions.", {"entities": [(0, 10, "SECTOR")]}),
    ("The aerospace sector is investing in innovative space travel technologies.", {"entities": [(4, 12, "SECTOR")]}),
    ("Retail technology is advancing with smart supply chain solutions.", {"entities": [(0, 6, "SECTOR")]}),
    ("The energy sector is developing advanced energy efficiency solutions.", {"entities": [(4, 10, "SECTOR")]}),
    ("The media industry is innovating with interactive content.", {"entities": [(4, 9, "SECTOR")]}),
    ("The financial services sector is embracing new fintech innovations.", {"entities": [(4, 17, "SECTOR")]}),
    ("Retail technology is evolving with AI for personalized experiences.", {"entities": [(0, 6, "SECTOR")]}),
    ("The aerospace industry is working on cutting-edge propulsion technologies.", {"entities": [(4, 12, "SECTOR")]}),
    ("The defense sector is enhancing its capabilities with advanced technologies.", {"entities": [(4, 11, "SECTOR")]}),
    ("The healthcare sector is integrating AI for personalized medicine.", {"entities": [(4, 12, "SECTOR")]}),
    ("Retail technology is innovating with AI for enhanced shopping experiences.", {"entities": [(0, 6, "SECTOR")]}),
    ("The media industry is focusing on new digital storytelling formats.", {"entities": [(4, 9, "SECTOR")]}),
    ("The aerospace sector is advancing with new space exploration systems.", {"entities": [(4, 12, "SECTOR")]}),
    ("Retail technology is incorporating AI for better customer insights.", {"entities": [(0, 6, "SECTOR")]}),
    ("The defense sector is focusing on next-gen security technologies.", {"entities": [(4, 11, "SECTOR")]}),
    ("The healthcare industry is expanding with AI-driven health solutions.", {"entities": [(4, 12, "SECTOR")]}),
    ("The energy sector is investing in advanced wind energy technology.", {"entities": [(4, 10, "SECTOR")]}),
    ("The aerospace industry is developing new satellite-based systems.", {"entities": [(4, 12, "SECTOR")]}),
    ("Retail technology is advancing with innovative AI applications.", {"entities": [(0, 6, "SECTOR")]}),
    ("The media industry is exploring new VR content formats.", {"entities": [(4, 9, "SECTOR")]}),
    ("The defense sector is enhancing its capabilities with AI for better security.", {"entities": [(4, 11, "SECTOR")]}),
    ("The healthcare field is focusing on next-gen health technologies.", {"entities": [(0, 10, "SECTOR")]}),
    ("The financial sector is investing in new blockchain technologies.", {"entities": [(4, 12, "SECTOR")]}),
    ("Retail technology is evolving with next-gen AI solutions.", {"entities": [(0, 6, "SECTOR")]}),
    ("The aerospace industry is advancing with new space research technologies.", {"entities": [(4, 12, "SECTOR")]}),
    ("The media sector is expanding with new forms of digital content.", {"entities": [(4, 9, "SECTOR")]}),
    ("The defense sector is focusing on AI-driven security enhancements.", {"entities": [(4, 11, "SECTOR")]}),
    ("The energy sector is developing advanced energy storage solutions.", {"entities": [(4, 10, "SECTOR")]}),
    ("Retail technology is innovating with new AI-driven strategies.", {"entities": [(0, 6, "SECTOR")]}),
    ("The aerospace industry is working on advanced space technologies.", {"entities": [(4, 12, "SECTOR")]}),
    ("The media industry is integrating VR for enhanced user engagement.", {"entities": [(4, 9, "SECTOR")]}),
    ("The defense sector is advancing with new AI-based defense systems.", {"entities": [(4, 11, "SECTOR")]}),
    ("The healthcare field is evolving with AI for personalized treatment.", {"entities": [(0, 10, "SECTOR")]}),
    ("The energy industry is innovating with cutting-edge renewable solutions.", {"entities": [(4, 5, "SECTOR")]}),
    ("Retail technology is advancing with new AI-powered systems.", {"entities": [(0, 6, "SECTOR")]}),
    ("The aerospace sector is developing innovative space propulsion systems.", {"entities": [(4, 12, "SECTOR")]}),
    ("The media industry is exploring next-gen digital engagement tools.", {"entities": [(4, 9, "SECTOR")]}),
    ("The defense sector is enhancing its capabilities with new AI technologies.", {"entities": [(4, 11, "SECTOR")]}),
    ("The healthcare industry is focusing on advanced health technologies.", {"entities": [(4, 12, "SECTOR")]}),
    ("The financial services sector is integrating new AI tools for better customer experience.", {"entities": [(4, 17, "SECTOR")]}),
    ("Retail technology is innovating with smart data analytics.", {"entities": [(0, 6, "SECTOR")]}),
    ("The aerospace industry is advancing with new space technology developments.", {"entities": [(4, 12, "SECTOR")]}),
    ("The energy sector is developing cutting-edge energy storage solutions.", {"entities": [(4, 10, "SECTOR")]}),
    ("Retail technology is evolving with AI-driven insights.", {"entities": [(0, 6, "SECTOR")]}),
    ("The media industry is focusing on new interactive content formats.", {"entities": [(4, 9, "SECTOR")]}),
    ("The healthcare field is advancing with innovative diagnostic tools.", {"entities": [(0, 10, "SECTOR")]}),
    ("The aerospace sector is working on advanced propulsion technologies.", {"entities": [(4, 12, "SECTOR")]}),
    ("The defense sector is integrating AI for enhanced security measures.", {"entities": [(4, 11, "SECTOR")]}),
    ("Retail technology is advancing with innovative customer solutions.", {"entities": [(0, 6, "SECTOR")]}),
    ("The energy sector is investing in advanced solar energy technologies.", {"entities": [(4, 10, "SECTOR")]}),
    ("The financial sector is focusing on next-gen blockchain applications.", {"entities": [(4, 12, "SECTOR")]}),
    ("Retail technology is evolving with next-gen AI-driven innovations.", {"entities": [(0, 6, "SECTOR")]}),
    ("The media industry is developing new virtual reality experiences.", {"entities": [(4, 9, "SECTOR")]}),
    ("The defense sector is advancing with AI-driven defense solutions.", {"entities": [(4, 11, "SECTOR")]}),
    ("The healthcare industry is integrating AI for advanced diagnostics.", {"entities": [(4, 12, "SECTOR")]}),
    ("The aerospace sector is advancing with cutting-edge space exploration technologies.", {"entities": [(4, 12, "SECTOR")]}),
    ("Retail technology is innovating with smart AI-driven solutions.", {"entities": [(0, 6, "SECTOR")]}),
    ("The media sector is expanding with new digital engagement tools.", {"entities": [(4, 9, "SECTOR")]}),
    ("The defense industry is enhancing its capabilities with next-gen AI technologies.", {"entities": [(4, 11, "SECTOR")]}),
    ("The energy sector is developing advanced renewable energy technologies.", {"entities": [(4, 10, "SECTOR")]}),
    ("The aerospace industry is working on new space propulsion technologies.", {"entities": [(4, 12, "SECTOR")]}),
    ("Retail technology is advancing with AI-powered customer solutions.", {"entities": [(0, 6, "SECTOR")]}),
    ("The media industry is focusing on immersive digital content.", {"entities": [(4, 9, "SECTOR")]}),
    ("The defense sector is integrating advanced AI for security applications.", {"entities": [(4, 11, "SECTOR")]}),
    ("The healthcare field is focusing on AI for personalized treatment.", {"entities": [(0, 10, "SECTOR")]}),
    ("The aerospace industry is investing in advanced space technologies.", {"entities": [(4, 12, "SECTOR")]}),
    ("Retail technology is evolving with new AI-driven solutions.", {"entities": [(0, 6, "SECTOR")]}),
    ("The media industry is expanding with new VR content formats.", {"entities": [(4, 9, "SECTOR")]}),
    ("The defense sector is advancing with new AI-based defense systems.", {"entities": [(4, 11, "SECTOR")]}),
    ("The healthcare industry is innovating with AI-powered diagnostics.", {"entities": [(4, 12, "SECTOR")]}),
    ("The aerospace sector is advancing with new space technologies.", {"entities": [(4, 12, "SECTOR")]}),
    ("The energy industry is focusing on advanced energy storage technologies.", {"entities": [(4, 5, "SECTOR")]}),
    ("Retail technology is innovating with smart retail systems.", {"entities": [(0, 6, "SECTOR")]}),
    ("The media industry is exploring next-gen VR content.", {"entities": [(4, 9, "SECTOR")]}),
    ("The defense sector is focusing on AI-driven security solutions.", {"entities": [(4, 11, "SECTOR")]}),
    ("The healthcare industry is investing in advanced health technologies.", {"entities": [(4, 12, "SECTOR")]}),
    ("The aerospace industry is advancing with new propulsion systems.", {"entities": [(4, 12, "SECTOR")]}),
    ("Retail technology is evolving with innovative AI strategies.", {"entities": [(0, 6, "SECTOR")]}),
    ("The media industry is innovating with new digital media formats.", {"entities": [(4, 9, "SECTOR")]}),
    ("The defense sector is developing advanced AI-based systems.", {"entities": [(4, 11, "SECTOR")]}),
    ("The healthcare field is integrating new AI-powered health solutions.", {"entities": [(0, 10, "SECTOR")]}),
    ("Retail technology is advancing with smart customer solutions.", {"entities": [(0, 6, "SECTOR")]}),
    ("The aerospace sector is focusing on new space research technologies.", {"entities": [(4, 12, "SECTOR")]}),
    ("The media industry is exploring innovative VR content experiences.", {"entities": [(4, 9, "SECTOR")]}),
    ("The defense sector is integrating AI for enhanced security measures.", {"entities": [(4, 11, "SECTOR")]}),
    ("The healthcare industry is innovating with AI-driven medical research.", {"entities": [(4, 12, "SECTOR")]}),
    ("Retail technology is evolving with new AI-based solutions.", {"entities": [(0, 6, "SECTOR")]}),
    ("The aerospace industry is investing in advanced space travel technologies.", {"entities": [(4, 12, "SECTOR")]}),
    ("The energy sector is advancing with new energy efficiency solutions.", {"entities": [(4, 10, "SECTOR")]}),
    ("The media industry is innovating with next-gen digital formats.", {"entities": [(4, 9, "SECTOR")]}),
    ("The defense sector is focusing on AI-driven defense solutions.", {"entities": [(4, 11, "SECTOR")]}),
    ("The healthcare field is integrating new AI-powered health technologies.", {"entities": [(0, 10, "SECTOR")]}),
    ("The aerospace sector is developing advanced space propulsion systems.", {"entities": [(4, 12, "SECTOR")]}),
    ("Retail technology is advancing with smart AI-powered solutions.", {"entities": [(0, 6, "SECTOR")]}),
    ("The media industry is expanding with innovative digital experiences.", {"entities": [(4, 9, "SECTOR")]}),
    ("The defense sector is enhancing its capabilities with AI-driven security solutions.", {"entities": [(4, 11, "SECTOR")]}),
    ("The healthcare industry is innovating with advanced health technologies.", {"entities": [(4, 12, "SECTOR")]}),
    ("The aerospace industry is investing in new space research technologies.", {"entities": [(4, 12, "SECTOR")]}),
    ("Retail technology is innovating with next-gen AI-driven customer solutions.", {"entities": [(0, 6, "SECTOR")]}),
    ("The media industry is focusing on next-gen digital content.", {"entities": [(4, 9, "SECTOR")]}),
    ("The defense sector is advancing with new AI-based security technologies.", {"entities": [(4, 11, "SECTOR")]}),
    ("The healthcare field is integrating new AI technologies for personalized medicine.", {"entities": [(0, 10, "SECTOR")]}),
    ("The aerospace sector is advancing with cutting-edge space technologies.", {"entities": [(4, 12, "SECTOR")]}),
    ("Retail technology is evolving with innovative AI solutions.", {"entities": [(0, 6, "SECTOR")]}),
    ("The media industry is developing next-gen VR content.", {"entities": [(4, 9, "SECTOR")]}),
    ("The defense sector is focusing on AI-driven security enhancements.", {"entities": [(4, 11, "SECTOR")]}),
    ("The healthcare industry is advancing with AI for improved diagnostics.", {"entities": [(4, 12, "SECTOR")]}),
    ("The aerospace industry is working on advanced space research technologies.", {"entities": [(4, 12, "SECTOR")]}),
    ("Retail technology is innovating with smart AI-driven systems.", {"entities": [(0, 6, "SECTOR")]}),
    ("The media industry is expanding with innovative digital experiences.", {"entities": [(4, 9, "SECTOR")]}),
    ("The defense sector is enhancing its capabilities with advanced AI technologies.", {"entities": [(4, 11, "SECTOR")]}),
    ("The healthcare field is focusing on new AI-powered health solutions.", {"entities": [(0, 10, "SECTOR")]}),
    ("The aerospace industry is developing advanced space propulsion systems.", {"entities": [(4, 12, "SECTOR")]}),
    ("Retail technology is evolving with new AI-driven insights.", {"entities": [(0, 6, "SECTOR")]}),
    ("The media industry is innovating with next-gen VR content formats.", {"entities": [(4, 9, "SECTOR")]}),
    ("The defense sector is advancing with AI-based defense solutions.", {"entities": [(4, 11, "SECTOR")]}),
    ("The healthcare industry is integrating new AI-driven medical technologies.", {"entities": [(4, 12, "SECTOR")]}),
    ("The aerospace sector is advancing with cutting-edge space technologies.", {"entities": [(4, 12, "SECTOR")]}),
    ("Retail technology is innovating with new AI-driven systems.", {"entities": [(0, 6, "SECTOR")]}),
    ("The media industry is focusing on immersive digital content.", {"entities": [(4, 9, "SECTOR")]}),
    ("The defense sector is integrating AI for advanced security solutions.", {"entities": [(4, 11, "SECTOR")]}),
    ("The healthcare field is evolving with AI-driven health solutions.", {"entities": [(0, 10, "SECTOR")]}),
    ("The aerospace sector is developing advanced space propulsion technologies.", {"entities": [(4, 12, "SECTOR")]}),
    ("Retail technology is evolving with AI-based customer solutions.", {"entities": [(0, 6, "SECTOR")]}),
    ("The media industry is advancing with innovative VR content formats.", {"entities": [(4, 9, "SECTOR")]}),
    ("The defense sector is focusing on new AI-driven security measures.", {"entities": [(4, 11, "SECTOR")]}),
    ("The healthcare industry is innovating with AI-powered diagnostic tools.", {"entities": [(4, 12, "SECTOR")]}),
    ("The aerospace sector is investing in new space technologies.", {"entities": [(4, 12, "SECTOR")]}),
    ("Retail technology is advancing with next-gen AI-driven solutions.", {"entities": [(0, 6, "SECTOR")]}),
    ("The media industry is integrating VR for new digital experiences.", {"entities": [(4, 9, "SECTOR")]}),
    ("The defense sector is enhancing its capabilities with advanced AI technologies.", {"entities": [(4, 11, "SECTOR")]}),
    ("The healthcare field is evolving with new AI-driven health technologies.", {"entities": [(0, 10, "SECTOR")]}),
    ("The aerospace sector is advancing with innovative space propulsion technologies.", {"entities": [(4, 12, "SECTOR")]}),
    ("Retail technology is innovating with smart AI-driven systems.", {"entities": [(0, 6, "SECTOR")]}),
    ("The media industry is focusing on next-gen digital content formats.", {"entities": [(4, 9, "SECTOR")]}),
    ("The defense sector is advancing with new AI-driven security solutions.", {"entities": [(4, 11, "SECTOR")]}),
    ("The healthcare industry is integrating new AI technologies for improved diagnostics.", {"entities": [(4, 12, "SECTOR")]}),
    ("The aerospace sector is focusing on advanced space technologies.", {"entities": [(4, 12, "SECTOR")]}),
    ("Retail technology is evolving with AI for better customer insights.", {"entities": [(0, 6, "SECTOR")]}),
    ("The media industry is innovating with next-gen digital formats.", {"entities": [(4, 9, "SECTOR")]}),
    ("The defense sector is integrating advanced AI-driven security measures.", {"entities": [(4, 11, "SECTOR")]}),
    ("The healthcare industry is developing new AI-powered health solutions.", {"entities": [(4, 12, "SECTOR")]}),
    ("The aerospace sector is advancing with cutting-edge space research technologies.", {"entities": [(4, 12, "SECTOR")]}),
    ("Retail technology is innovating with AI-powered customer solutions.", {"entities": [(0, 6, "SECTOR")]}),
    ("The media industry is focusing on new VR content formats.", {"entities": [(4, 9, "SECTOR")]}),
    ("The defense sector is enhancing its capabilities with advanced AI-based systems.", {"entities": [(4, 11, "SECTOR")]}),
    ("The healthcare field is advancing with AI-driven health technologies.", {"entities": [(0, 10, "SECTOR")]}),
    ("The aerospace industry is investing in advanced space technologies.", {"entities": [(4, 12, "SECTOR")]}),
    ("Retail technology is evolving with innovative AI-driven systems.", {"entities": [(0, 6, "SECTOR")]}),
    ("The media industry is integrating new digital content formats.", {"entities": [(4, 9, "SECTOR")]}),
    ("The defense sector is advancing with next-gen AI security systems.", {"entities": [(4, 11, "SECTOR")]}),
    ("The healthcare industry is innovating with advanced AI-driven diagnostic tools.", {"entities": [(4, 12, "SECTOR")]}),
    ("The aerospace sector is developing innovative space propulsion technologies.", {"entities": [(4, 12, "SECTOR")]}),
    ("Retail technology is advancing with smart AI-driven solutions.", {"entities": [(0, 6, "SECTOR")]}),
    ("The media industry is focusing on next-gen immersive digital content.", {"entities": [(4, 9, "SECTOR")]}),
    ("The defense sector is integrating advanced AI for security applications.", {"entities": [(4, 11, "SECTOR")]}),
    ("The healthcare field is evolving with innovative AI-driven health technologies.", {"entities": [(0, 10, "SECTOR")]}),
    ("The aerospace industry is advancing with next-gen space technologies.", {"entities": [(4, 12, "SECTOR")]}),
    ("Retail technology is innovating with new AI-driven solutions.", {"entities": [(0, 6, "SECTOR")]}),
    ("The media industry is expanding with new forms of VR content.", {"entities": [(4, 9, "SECTOR")]}),
    ("The defense sector is focusing on advanced AI for security enhancements.", {"entities": [(4, 11, "SECTOR")]}),
    ("The healthcare industry is advancing with new AI-powered diagnostic tools.", {"entities": [(4, 12, "SECTOR")]}),
    ("The aerospace sector is working on innovative space technologies.", {"entities": [(4, 12, "SECTOR")]}),
    ("Retail technology is evolving with next-gen AI solutions.", {"entities": [(0, 6, "SECTOR")]}),
    ("The media industry is innovating with new digital content formats.", {"entities": [(4, 9, "SECTOR")]}),
    ("The defense sector is advancing with AI-driven security solutions.", {"entities": [(4, 11, "SECTOR")]}),
    ("The healthcare field is integrating AI technologies for improved health outcomes.", {"entities": [(0, 10, "SECTOR")]}),
    ("The aerospace industry is focusing on next-gen space propulsion systems.", {"entities": [(4, 12, "SECTOR")]}),
    ("Retail technology is innovating with smart AI-driven systems.", {"entities": [(0, 6, "SECTOR")]}),
    ("The media industry is expanding with next-gen VR content formats.", {"entities": [(4, 9, "SECTOR")]}),
    ("The defense sector is focusing on advanced AI-based security solutions.", {"entities": [(4, 11, "SECTOR")]}),
    ("The healthcare industry is integrating new AI-driven health solutions.", {"entities": [(4, 12, "SECTOR")]}),
    ("The aerospace sector is developing advanced space research technologies.", {"entities": [(4, 12, "SECTOR")]}),
    ("Retail technology is advancing with innovative AI systems.", {"entities": [(0, 6, "SECTOR")]}),
    ("The media industry is focusing on immersive digital content.", {"entities": [(4, 9, "SECTOR")]}),
    ("The defense sector is enhancing its capabilities with AI-based security systems.", {"entities": [(4, 11, "SECTOR")]}),
    ("The healthcare field is evolving with next-gen AI technologies.", {"entities": [(0, 10, "SECTOR")]}),
    ("The aerospace industry is advancing with new space research solutions.", {"entities": [(4, 12, "SECTOR")]}),
    ("Retail technology is innovating with AI-driven solutions.", {"entities": [(0, 6, "SECTOR")]}),
    ("The media industry is expanding with innovative digital formats.", {"entities": [(4, 9, "SECTOR")]}),
    ("The defense sector is focusing on next-gen AI security measures.", {"entities": [(4, 11, "SECTOR")]}),
    ("The healthcare industry is advancing with advanced AI-based health technologies.", {"entities": [(4, 12, "SECTOR")]}),
    ("The aerospace sector is focusing on cutting-edge space propulsion systems.", {"entities": [(4, 12, "SECTOR")]}),
    ("Retail technology is evolving with smart AI-powered systems.", {"entities": [(0, 6, "SECTOR")]}),
    ("The media industry is integrating new VR content formats.", {"entities": [(4, 9, "SECTOR")]}),
    ("The defense sector is innovating with AI-driven security solutions.", {"entities": [(4, 11, "SECTOR")]}),
    ("The healthcare field is advancing with new AI-driven health technologies.", {"entities": [(0, 10, "SECTOR")]}),
    ("The aerospace industry is developing advanced space propulsion technologies.", {"entities": [(4, 12, "SECTOR")]}),
    ("Retail technology is advancing with innovative AI-driven solutions.", {"entities": [(0, 6, "SECTOR")]}),
    ("The media industry is expanding with immersive digital content formats.", {"entities": [(4, 9, "SECTOR")]}),
    ("The defense sector is focusing on next-gen AI-driven security systems.", {"entities": [(4, 11, "SECTOR")]}),
    ("The healthcare industry is integrating AI technologies for improved medical outcomes.", {"entities": [(4, 12, "SECTOR")]}),
    ("The aerospace sector is advancing with next-gen space technologies.", {"entities": [(4, 12, "SECTOR")]}),
    ("Retail technology is innovating with AI-driven customer insights.", {"entities": [(0, 6, "SECTOR")]}),
    ("The media industry is focusing on innovative digital content formats.", {"entities": [(4, 9, "SECTOR")]}),
    ("The defense sector is advancing with AI-based security solutions.", {"entities": [(4, 11, "SECTOR")]}),
    ("The healthcare field is evolving with AI-powered health solutions.", {"entities": [(0, 10, "SECTOR")]}),
    ("The aerospace industry is investing in new space research technologies.", {"entities": [(4, 12, "SECTOR")]}),
    ("Retail technology is advancing with AI-powered solutions.", {"entities": [(0, 6, "SECTOR")]}),
    ("The media industry is expanding with next-gen digital formats.", {"entities": [(4, 9, "SECTOR")]}),
    ("The defense sector is focusing on advanced AI-driven security measures.", {"entities": [(4, 11, "SECTOR")]}),
    ("The healthcare industry is innovating with AI-driven diagnostic solutions.", {"entities": [(4, 12, "SECTOR")]}),
    ("The aerospace sector is advancing with cutting-edge space technologies.", {"entities": [(4, 12, "SECTOR")]}),
    ("Retail technology is innovating with smart AI solutions.", {"entities": [(0, 6, "SECTOR")]}),
    ("The media industry is focusing on next-gen immersive digital experiences.", {"entities": [(4, 9, "SECTOR")]}),
    ("The defense sector is developing advanced AI security technologies.", {"entities": [(4, 11, "SECTOR")]}),
    ("The healthcare field is evolving with innovative AI-powered medical technologies.", {"entities": [(0, 10, "SECTOR")]}),
    ("The aerospace industry is investing in innovative space technologies.", {"entities": [(4, 12, "SECTOR")]}),
    ("Retail technology is advancing with new AI-powered systems.", {"entities": [(0, 6, "SECTOR")]}),
    ("The media industry is expanding with new digital engagement tools.", {"entities": [(4, 9, "SECTOR")]}),
    ("The defense sector is innovating with advanced AI-driven security solutions.", {"entities": [(4, 11, "SECTOR")]}),
    ("The healthcare industry is integrating AI-driven technologies for better diagnostics.", {"entities": [(4, 12, "SECTOR")]}),
    ("The aerospace sector is focusing on new space technologies.", {"entities": [(4, 12, "SECTOR")]}),
    ("Retail technology is innovating with smart AI-based systems.", {"entities": [(0, 6, "SECTOR")]}),
    ("The media industry is advancing with innovative VR content.", {"entities": [(4, 9, "SECTOR")]}),
    ("The defense sector is developing new AI-driven security systems.", {"entities": [(4, 11, "SECTOR")]}),
    ("The healthcare industry is focusing on next-gen AI-powered health technologies.", {"entities": [(4, 12, "SECTOR")]}),
    ("The aerospace sector is advancing with next-gen space research technologies.", {"entities": [(4, 12, "SECTOR")]}),
    ("Retail technology is evolving with AI-driven customer insights.", {"entities": [(0, 6, "SECTOR")]}),
    ("The media industry is innovating with advanced digital content formats.", {"entities": [(4, 9, "SECTOR")]}),
    ("The defense sector is enhancing its capabilities with AI-driven security technologies.", {"entities": [(4, 11, "SECTOR")]}),
    ("The healthcare field is integrating innovative AI-driven medical solutions.", {"entities": [(0, 10, "SECTOR")]}),
    ("The aerospace industry is working on advanced space propulsion technologies.", {"entities": [(4, 12, "SECTOR")]}),
    ("Retail technology is innovating with new AI-powered systems.", {"entities": [(0, 6, "SECTOR")]}),
    ("The media industry is focusing on immersive VR content formats.", {"entities": [(4, 9, "SECTOR")]}),
    ("The defense sector is advancing with new AI-driven security systems.", {"entities": [(4, 11, "SECTOR")]}),
    ("The healthcare industry is integrating AI technologies for enhanced medical outcomes.", {"entities": [(4, 12, "SECTOR")]}),
    ("The aerospace sector is investing in next-gen space technologies.", {"entities": [(4, 12, "SECTOR")]}),
    ("Retail technology is evolving with innovative AI systems.", {"entities": [(0, 6, "SECTOR")]}),
    ("The media industry is expanding with new VR content formats.", {"entities": [(4, 9, "SECTOR")]}),
    ("The defense sector is developing advanced AI-driven security solutions.", {"entities": [(4, 11, "SECTOR")]}),
    ("The healthcare field is advancing with AI-powered health technologies.", {"entities": [(0, 10, "SECTOR")]}),
    ("The aerospace industry is working on new space technologies.", {"entities": [(4, 12, "SECTOR")]}),
    ("Retail technology is innovating with smart AI-driven solutions.", {"entities": [(0, 6, "SECTOR")]}),
    ("The media industry is focusing on advanced digital content formats.", {"entities": [(4, 9, "SECTOR")]}),
    ("The defense sector is enhancing its capabilities with AI-based security measures.", {"entities": [(4, 11, "SECTOR")]}),
    ("The healthcare industry is integrating new AI-driven health technologies.", {"entities": [(4, 12, "SECTOR")]}),
    ("The aerospace sector is advancing with innovative space research technologies.", {"entities": [(4, 12, "SECTOR")]}),
    ("Retail technology is evolving with next-gen AI solutions.", {"entities": [(0, 6, "SECTOR")]}),
    ("The media industry is expanding with new digital content formats.", {"entities": [(4, 9, "SECTOR")]}),
    ("The defense sector is innovating with AI-driven security technologies.", {"entities": [(4, 11, "SECTOR")]}),
    ("The healthcare field is focusing on advanced AI-powered health solutions.", {"entities": [(0, 10, "SECTOR")]}),
    ("The aerospace industry is developing new space research technologies.", {"entities": [(4, 12, "SECTOR")]}),
    ("Retail technology is advancing with innovative AI-based solutions.", {"entities": [(0, 6, "SECTOR")]}),
    ("The media industry is innovating with next-gen digital content formats.", {"entities": [(4, 9, "SECTOR")]}),
    ("The defense sector is advancing with new AI-based security measures.", {"entities": [(4, 11, "SECTOR")]}),
    ("The healthcare industry is integrating advanced AI technologies for improved medical outcomes.", {"entities": [(4, 12, "SECTOR")]}),
    ("The aerospace sector is focusing on next-gen space propulsion technologies.", {"entities": [(4, 12, "SECTOR")]}),
    ("Retail technology is evolving with smart AI-powered systems.", {"entities": [(0, 6, "SECTOR")]}),
    ("The media industry is expanding with new forms of VR content.", {"entities": [(4, 9, "SECTOR")]}),
    ("The defense sector is focusing on advanced AI-driven security systems.", {"entities": [(4, 11, "SECTOR")]}),
    ("The healthcare field is innovating with new AI-driven health technologies.", {"entities": [(0, 10, "SECTOR")]}),
    ("The aerospace industry is advancing with next-gen space research solutions.", {"entities": [(4, 12, "SECTOR")]}),
    ("Retail technology is innovating with AI-based solutions.", {"entities": [(0, 6, "SECTOR")]}),
    ("The media industry is developing new digital content formats.", {"entities": [(4, 9, "SECTOR")]}),
    ("The defense sector is enhancing its capabilities with AI-driven security solutions.", {"entities": [(4, 11, "SECTOR")]}),
    ("The healthcare industry is advancing with innovative AI-based diagnostic tools.", {"entities": [(4, 12, "SECTOR")]}),
    ("The aerospace sector is focusing on advanced space propulsion systems.", {"entities": [(4, 12, "SECTOR")]}),
    ("Retail technology is evolving with innovative AI-driven customer insights.", {"entities": [(0, 6, "SECTOR")]}),
    ("The media industry is expanding with new digital formats.", {"entities": [(4, 9, "SECTOR")]}),
    ("The defense sector is integrating AI-driven security measures.", {"entities": [(4, 11, "SECTOR")]}),
    ("The healthcare industry is innovating with advanced AI-powered health solutions.", {"entities": [(4, 12, "SECTOR")]}),
    ("The aerospace sector is advancing with next-gen space research technologies.", {"entities": [(4, 12, "SECTOR")]}),
    ("Retail technology is innovating with next-gen AI systems.", {"entities": [(0, 6, "SECTOR")]}),
    ("The media industry is focusing on immersive digital content formats.", {"entities": [(4, 9, "SECTOR")]}),
    ("The defense sector is developing advanced AI security solutions.", {"entities": [(4, 11, "SECTOR")]}),
    ("The healthcare field is integrating AI-driven health technologies.", {"entities": [(0, 10, "SECTOR")]}),
    ("The aerospace industry is advancing with cutting-edge space research technologies.", {"entities": [(4, 12, "SECTOR")]}),
    ("Retail technology is evolving with innovative AI-powered solutions.", {"entities": [(0, 6, "SECTOR")]}),
    ("The media industry is expanding with next-gen digital content formats.", {"entities": [(4, 9, "SECTOR")]}),
    ("The defense sector is enhancing its capabilities with AI-based security systems.", {"entities": [(4, 11, "SECTOR")]}),
    ("The healthcare industry is integrating new AI-driven health technologies.", {"entities": [(4, 12, "SECTOR")]}),
    ("The aerospace sector is developing innovative space propulsion systems.", {"entities": [(4, 12, "SECTOR")]}),
    ("Retail technology is advancing with new AI-driven systems.", {"entities": [(0, 6, "SECTOR")]}),
    ("The media industry is innovating with advanced digital content formats.", {"entities": [(4, 9, "SECTOR")]}),
    ("The defense sector is advancing with next-gen AI-driven security technologies.", {"entities": [(4, 11, "SECTOR")]}),
    ("The healthcare field is focusing on new AI-driven health technologies.", {"entities": [(0, 10, "SECTOR")]}),
    ("The aerospace industry is investing in advanced space propulsion systems.", {"entities": [(4, 12, "SECTOR")]}),
    ("Retail technology is innovating with smart AI-driven systems.", {"entities": [(0, 6, "SECTOR")]}),
    ("The media industry is expanding with next-gen digital content.", {"entities": [(4, 9, "SECTOR")]}),
    ("The defense sector is integrating new AI-driven security technologies.", {"entities": [(4, 11, "SECTOR")]}),
    ("The healthcare industry is advancing with innovative AI technologies for diagnostics.", {"entities": [(4, 12, "SECTOR")]}),
    ("The aerospace sector is focusing on next-gen space research technologies.", {"entities": [(4, 12, "SECTOR")]}),
    ("Retail technology is evolving with new AI-based solutions.", {"entities": [(0, 6, "SECTOR")]}),
    ("The media industry is innovating with next-gen VR content formats.", {"entities": [(4, 9, "SECTOR")]}),
    ("The defense sector is developing AI-driven security systems.", {"entities": [(4, 11, "SECTOR")]}),
    ("The healthcare industry is integrating advanced AI-driven medical solutions.", {"entities": [(4, 12, "SECTOR")]}),
    ("The aerospace sector is investing in advanced space technologies.", {"entities": [(4, 12, "SECTOR")]}),
    ("Retail technology is advancing with innovative AI-powered systems.", {"entities": [(0, 6, "SECTOR")]}),
    ("The media industry is expanding with new forms of immersive digital content.", {"entities": [(4, 9, "SECTOR")]}),
    ("The defense sector is focusing on next-gen AI security technologies.", {"entities": [(4, 11, "SECTOR")]}),
    ("The healthcare field is innovating with new AI-driven health technologies.", {"entities": [(0, 10, "SECTOR")]}),
    ("The aerospace industry is working on new space propulsion systems.", {"entities": [(4, 12, "SECTOR")]}),
    ("Retail technology is evolving with innovative AI-driven solutions.", {"entities": [(0, 6, "SECTOR")]}),
    ("The media industry is focusing on advanced digital content formats.", {"entities": [(4, 9, "SECTOR")]}),
    ]